#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
CHECK_ID_extra91="9.1"
CHECK_TITLE_extra91="[extra91] Check for internet facing Subnets (Not Scored) (Not part of CIS benchmark)"
CHECK_SCORED_extra91="NOT_SCORED"
CHECK_TYPE_extra91="EXTRA"
CHECK_SEVERITY_extra91="Medium"
CHECK_ASFF_RESOURCE_TYPE_extra91="Subnet"
CHECK_SERVICENAME_extra91="ec2"
CHECK_RISK_extra91='Publicly accessible subnets could expose sensitive data to bad actors.'
CHECK_REMEDIATION_extra91='Ensure the subnet should be publicly accessible. If publicly exposed ensure proper instance security.'
CHECK_DOC_extra91='https://docs.aws.amazon.com/waf/latest/developerguide/web-acl-associating-aws-resource.html'
CHECK_CAF_EPIC_extra91='Data Protection'

extra91(){
  LF=$'\n'
  # "Check for internet facing Subnets (Not Scored) (Not part of CIS benchmark)"
  textInfo "Looking for Subnets in all regions...  "
  for regx in $REGIONS; do
    LIST_OF_SUBNETS=$($AWSCLI ec2 describe-subnets $PROFILE_OPT --region $regx --query 'Subnets[*].[SubnetId]' --output text | sort)
    LIST_OF_IGWS=$($AWSCLI ec2 describe-internet-gateways $PROFILE_OPT --region $regx --query 'InternetGateways[*].[InternetGatewayId]' --output text)
    IGW_STRING=()
    for IGW in $LIST_OF_IGWS;do IGW_STRING=${IGW_STRING:+$IGW_STRING,}$IGW; done
    LIST_OF_PUB_VPCS=$($AWSCLI ec2 describe-route-tables $PROFILE_OPT --region $regx --filters Name=route.gateway-id,Values=$IGW_STRING Name=association.main,Values=true --query 'RouteTables[*].[VpcId]' --output text | sort | uniq)
    PUB_VPC_STRING=()
    for VPC in $LIST_OF_PUB_VPCS;do PUB_VPC_STRING=${PUB_VPC_STRING:+$PUB_VPC_STRING,}$VPC; done
    # Build list of subnets that are associated with Route Tables containing and IGW route.
    LIST_OF_PUB_SUBNETS=$($AWSCLI ec2 describe-route-tables $PROFILE_OPT --region $regx --filters Name=route.gateway-id,Values=$IGW_STRING Name=association.main,Values=false --query 'RouteTables[*].Associations[*].[SubnetId]' --output text | grep -v None | sort | uniq)

    for SUBNET in $LIST_OF_SUBNETS; do
        # Is this subnet in the list of subnets associated with a public Route Table?
        if [[ ! "$LIST_OF_PUB_SUBNETS" == *"$SUBNET"* ]]; then
            # Is this subnet associated to a VPC with a public Route Table?
	    if [[ `$AWSCLI ec2 describe-subnets $PROFILE_OPT --region $regx --subnet-id $SUBNET --filter Name=vpc-id,Values=${PUB_VPC_STRING} --output text` ]]; then
		# This Subnet is in a VPC with a public Route Table, is it associated with a different RT?
		if [[ ! `$AWSCLI ec2 describe-route-tables $PROFILE_OPT --region $regx --filters Name=association.subnet-id,Values=${SUBNET} --query 'RouteTables[*].[SubnetId]' --output text` ]]; then
                    LIST_OF_PUB_SUBNETS=$"${LIST_OF_PUB_SUBNETS:+$LIST_OF_PUB_SUBNETS${LF}}${SUBNET}"
                fi
            fi
        fi
    done
    if [[ $LIST_OF_PUB_SUBNETS ]];then
      while read -r subnet;do
        SUBNET_NAME=$(echo $subnet | awk '{ print $1; }')
        textFail "$regx: SUBNET: $SUBNET_NAME is internet-facing!" "$regx"
      done <<< "$LIST_OF_PUB_SUBNETS"
      else
        textPass "$regx: no Internet Facing Subnets found" "$regx"
      fi
  done
}
